version: '2'
services:
    ui:
        build: ./ui
        volumes: 
            - ./ui:/opt/ui
        links:
            - api
        ports:
            - "4200:4200"
    api:
        build: ./api
        volumes: 
            - ./api:/opt/api
        ports:
            - "3000:3000"
    db:
        image: redis:alpine
        ports:
            - "6379:6379"